### PR TITLE
Feature/383 bill sort desc

### PR DESCRIPTION
**Pull request by ayeshamk**

### CODE REVIEW

**Review by aih — COMMENTED** [review]
>            if our_list[j][:3] < our_list[j+1][:3]:

This is the key line. I presume this is the 'congress' part of the bill number. Can you first get this into a `congress` variable, and check that it is in the correct form (i.e. that it is a 3 digit number, when parsed to an int?) That will make the sorting more robust and also the code easier to read.

**Comment by ayeshamk** [comment]
@aih is this deployed in prod now? I do not see the changes make any impact on the companion bills.

**Comment by aih** [comment]
It is deployed and working now.

**Comment by aih** [comment]
image

**Pull request merged**
