### PR TITLE
data export extra spaces issue fixed

### PR DESCRIPTION
**Pull request by ayeshamk**

### CODE REVIEW

**Comment by ayeshamk** [comment]
@aih is this deployed? I don't see the changes reflected in prod.

**Comment by aih** [comment]
Yes, prod is on the commit below as of yesterday. I ran `python manage.py collectstatic` and restarted the uwgi server. Maybe you need to refresh browser cache?

```
commit 4a40cb52e65c59cfe92d880c2dd15187d55a1ddf (HEAD -> main, origin/main)
Author: ayeshamk <ayesha.malika.khan@gmail.com>
Date:   Thu Sep 2 17:04:42 2021 -0400

    data export extra spaces issue (#566)
```

**Comment by ayeshamk** [comment]
the data export is clean for me locally.

image


@nkinaba @cybkong can you 2 confirm if it is working?

**Comment by ayeshamk** [comment]
@aih did anything change in DB? I do not see any records with multiple bills in the data anymore. This is for sponsors of related measures. Also do not see any data for Same Congress tab.
image

image

**Comment by aih** [comment]
I don't have any record for that bill. Other bills that I am familiar with have data:
image

**Pull request merged**
